const bcrypt = require('bcrypt');

const SALT_ROUNDS = 10;

/**
 * Hash a plaintext password with autogenerated salt
 * @function
 * @param {string} plaintextPassword - Text to hash
 * @returns {string} Hashed & salted password
 */
function hashPassword (plaintextPassword) {
  return bcrypt.hashSync(plaintextPassword, SALT_ROUNDS);
}

/**
 * Compares a plaintext password against hashed password 
 * @function
 * @param {string} plaintextPassword - Plaintext password
 * @param {string} hashedPassword - Hashed & salted Password
 * @returns {boolean} Whether the passwords match
 */
function checkPassword (plaintextPassword, hashedPassword) {
  return bcrypt.compareSync(plaintextPassword, hashedPassword);
}

module.exports = {
  hashPassword,
  checkPassword,
}
